src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Asset_Generated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Asset Generated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_ID__c</fullName>
        <inlineHelpText>SAP ID is supplied by the finance department</inlineHelpText>
        <label>SAP ID</label>
        <length>7</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>The Primary contact is the person with access to the website. There can only be one Primary Contact for each dealer account</inlineHelpText>
        <label>Primary Contact</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/classes/Hotrod_Dealer_Test.cls
@isTest(seeAllData=false)
public class Hotrod_Dealer_Test{
    @isTest(seeAllData=false)
    public static void new_contact_test() {
    	Account a = new Account(Name = 'TEST', Asset_Generated__c = true, SAP_ID__c = '9232323', External_Id__c = '1234567890', Phone = '01329874953', BillingCity = 'BillingCity', BillingStreet = 'BillingStreet', BillingPostalCode = 'BillingPostalCode');
        Database.insert(a);
        Contact c = new Contact(FirstName = 'FirstName', Phone = '01329874953', LastName = 'LastName', AccountID = a.Id, email = 'test@test.com', primary_contact__c = true);
        Database.insert(c);

        c.email = 'test2@test.com';
        Database.update(c);

        c.FirstName = 'test2';
        Database.update(c);
    }
}